# Generated by Django 4.0.6 on 2022-07-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ball', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('About', models.TextField(max_length=10000)),
            ],
        ),
    ]
